### ISSUE TITLE
Uncaught pexpect.EOF exception in set_unique_prompt()

### ISSUE THREAD

**Issue by aphexcx** [noahspurrier/pexpect#2]
When attempting to connect to a server without supplying a password (the password argument to login() is `''`), the connection seems to time out and later causes an `pexpect.EOF` error to be raised in set_unique_prompt().

A brief look at the code indicates that we are reaching the i=5 case in the 2nd phase of the login function, indicating a timeout or perhaps that the server is waiting for us to input our password. (We did, but our password is an empty string). But because this situation is ignored (this case is handled with a `pass`), we blithely continue with the login function causing set_unique_prompt to explode later. This seems to be by design, but then, why does set_unique_prompt not have exception handling for the resulting `pexpect.EOF` exception that is raised? 

Traceback follows:

```
Traceback (most recent call last):
  File "/home/aphex/tripit/devtools/bin/getmail", line 375, in <module>
    sys.exit(main(sys.argv))
  File "/home/aphex/tripit/devtools/bin/getmail", line 358, in main
    code = getmailbyguid(guid)
  File "/home/aphex/tripit/devtools/bin/getmail", line 143, in getmailbyguid
    session.login(archive, username, password='')
  File "/home/aphex/tripit/env/lib/python2.6/site-packages/pxssh.py", line 253, in login
    if not self.set_unique_prompt():
  File "/home/aphex/tripit/env/lib/python2.6/site-packages/pxssh.py", line 303, in set_unique_prompt
    i = self.expect ([TIMEOUT, self.PROMPT], timeout=10)
  File "/home/aphex/tripit/env/lib/python2.6/site-packages/pexpect.py", line 1316, in expect
    return self.expect_list(compiled_pattern_list, timeout, searchwindowsize)
  File "/home/aphex/tripit/env/lib/python2.6/site-packages/pexpect.py", line 1330, in expect_list
    return self.expect_loop(searcher_re(pattern_list), timeout, searchwindowsize)
  File "/home/aphex/tripit/env/lib/python2.6/site-packages/pexpect.py", line 1401, in expect_loop
    raise EOF (str(e) + '\n' + str(self))
pexpect.EOF: End Of File (EOF) in read_nonblocking(). Exception style platform.
<pxssh.pxssh object at 0x2355fd0>
version: 2.4 ($Revision: 516 $)
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-q', '-l', 'aphex', 'dmtest.corp.tripit.com']
searcher: searcher_re:
    0: TIMEOUT
    1: re.compile("\[PEXPECT\][\$\#] ")
buffer (last 100 chars): 
before (last 100 chars): 
PS1='[PEXPECT]\$ '

after: <class 'pexpect.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 37573
child_fd: 3
closed: False
timeout: 30
delimiter: <class 'pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
```

**Comment by aphexcx** [comment]
Interesting note: increasing the login_timeout parameter to 15 caused the following behavior: 
The script attempted to log in, and after a few seconds an OpenSSH GUI password window appeared in the foreground. A second or two after it appeared, though, the script terminated in the background with `ExceptionPxssh: password refused`. 

Two unexpected things here:
1) Why does that GUI window appear instead of a simple text password prompt showing up on the terminal?
2) If that GUI window is supposed to capture the password, shouldn't pxssh wait for it to be submitted rather than dying in the background with a `password refused` error?

Traceback follows:

```
Traceback (most recent call last):
  File "/home/afik/tripit/devtools/bin/getmail", line 375, in <module>
    sys.exit(main(sys.argv))
  File "/home/afik/tripit/devtools/bin/getmail", line 358, in main
    code = getmailbyguid(guid)
  File "/home/afik/tripit/devtools/bin/getmail", line 143, in getmailbyguid
    session.login(archive, username, password='', login_timeout=15)
  File "/home/afik/tripit/env/lib/python2.6/site-packages/pxssh.py", line 226, in login
    raise ExceptionPxssh ('password refused')
pxssh.ExceptionPxssh: password refused
```

**Comment by jquast** [comment]
Hi aphexcx, what if you were to pass the '-t' argument to ssh:

```
 -t      Force pseudo-tty allocation.  This can be used to execute arbi-
         trary screen-based programs on a remote machine, (...)
```

The SSH GUI password only appears when stdin does not appear to be terminal to ssh, but XDISPLAY is available. As for EOF -- i suspect that because stdin is not a terminal, and no "command argument" (such as /bin/bash) is supplied, that it doesn't really plan to do anything at all.
