### ISSUE TITLE
exception in child process propagates

### ISSUE THREAD

**Issue by brianmay** [noahspurrier/pexpect#4]
The code, simplified, is:

``` python
def _spawn(self,command,args=[]):
    ...
    if self.pid == 0: # Child
        ...
        os.exec...(...)
```

If an exception occurs if this child section, e.g. exec fails or any of the other instructions, the propagation is passed upwards to the caller, which is confusing because this is not the process that called the function. i.e. two processes return when you only expect one process to return.

This can be fixed by changing the child code to exit on exception:

``` python
def _spawn(self,command,args=[]):
    ...
    if self.pid == 0: # Child
        try:
            ...
            os.exec...(...)
        finally:
             sys.exit(1)
```

Note I have used finally here as exec should never return. So finally will only get executed if something went wrong.

**Comment by jquast** [comment]
I agree about the change of behavior; currently something like .interact() would hang on failure to exec*.

This can happen for instance if there are no more resources such as out of memory conditions, or the example provided below (Exec format error). I don't agree on the proposed solution, though, testing this, .interact() returns, no error is reported, and all you receive is an exit status of 1 with an empty line.

I made an empty file using touch, '/bin/liar', and made it executable. This is an error by the operating system in discovering how to execute a file without an ELF header or an ascii first line indicating which interpreter should be used.

> > > pexpect.spawn('/bin/liar').interact()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pexpect.py", line 467, in **init**
> > >     self._spawn(command, args)
> > >   File "pexpect.py", line 605, in _spawn
> > >     os.execv(self.command, self.args)
> > > OSError: [Errno 8] Exec format error
